### PR TITLE
added links for both badges

### PR DESCRIPTION
**Pull request by lkwg82**

### CODE REVIEW

**Comment by andidev** [comment]
Great! As you can see I released the new version. I'll update the docs later. I created a new github project for a new repository to keep backwardscompability and added some more drivers.

**Comment by andidev** [comment]
Please feel free to do more PR's if you need some more features. I'm quite open with changes as long as they do not break backwards compatibility.

**Comment by lkwg82** [comment]
> I'll update the docs later.
I don't like those sentences ;).

**Comment by andidev** [comment]
Hehe I know later means never though not this time! Working on it. I have to make another release of the webdriverextensions artifact first.

**Comment by andidev** [comment]
So it's done. Thanks again!

**Pull request merged**
