### PR TITLE
set the version of assertj to the version 2 release due to java 7 com…

### PR DESCRIPTION
**Pull request by lkwg82**
…patibility

seen in https://github.com/raskasa/metrics-okhttp/issues/15

### CODE REVIEW

**Comment by andidev** [comment]
Not sure if it's to smart to drop java 6 support yet since selenium still works with java 6. So maybe I'll downgrade this to 1.x later and add java 6 support again. Btw how come you removed the java 7 support in your other PR? Is there a valid reason for that?

**Comment by lkwg82** [comment]
java 7 support removed by using assertj 3 which uses Optionals and this breaks a compilation

**Comment by andidev** [comment]
Sorry I meant to ask why you removed java 6 support in your other PR. Though now I see that the latest version of selenium is actually compiled to java 7 so using java 7 as target is actually the right way to do it.

**Comment by lkwg82** [comment]
I did not see any jdk version pinning so I set it to the last supported version. I searched for any jdk minimum version and did not found one.

So it was by accident.

**Pull request merged**
