### PR TITLE
Pumano master plus polishing

### PR DESCRIPTION
**Pull request by andidev**
PR #19 marionette driver support added + removed chromdriver if case from detectBits + configured http client to ignore cookies to remove warning in logs

### CODE REVIEW

**Comment by andidev** [comment]
The only thing left to do is to create a webdriverextensions-maven-plugin-repository-3.0 repository and link it. This is needed since otherwise the older versions of the plugin will stop working.

**Comment by andidev** [comment]
Repo created 
See https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository-3.0
I also added the edgedriver so there is also a need for supporting non extracted files since it is downloaded as an uncompressed exe file.

**Comment by pumano** [comment]
I also add geckodriver to readme file. plz add that commit too

**Comment by andidev** [comment]
Thanks! I'll do that. I'll try to work on it tonight.

**Pull request merged**
