### PR TITLE
fixes tests / 32bit+64bit detection / download cache

### PR DESCRIPTION
**Pull request by lkwg82**
This fixes many tests.
This removes the special handling of 64bit only for linux.

Cheers Lars

P.S: would be nice, if you can make a release, if you are fine with that.

### CODE REVIEW

**Comment by lkwg82** [comment]
The download tests are very flaky, plz test it on your machine. We should change from many integration tests to much less.

**Comment by andidev** [comment]
Thanks! If you want I could give you access to this repo if you want to be a co-maintainer?

Unfortunately the phantomjs drivers fails since bitbucket probably dislikes the many downloads. Though the errors don't really say exactly what is goes wrong.

Yes the test should not be that integration heavy, your right. The HttpClient should probably be mocked somehow. Maybe wrapped in a class that could be replaced by a mocked implementation in the tests. 
Maybe you have a better idea?
Though don't have time to work on this right now though. Feel free to fix it somehow!

I'll do a release immediately!

**Comment by andidev** [comment]
By the way does the phantomjs drivers work without errors when using this plugin normally?

**Comment by andidev** [comment]
Okey I missed that you changed the 64bit check.
I'm not sure that the downloaded driver should be 64bit for internetexplorer driver if the OS is 64bit. The default internetexplorer version used on Windows 7 and 8 is 32bit. Windows 10 seems to use 64bit.

I guess phantomjs driver should be based on the OS bit version?

Any thoughts?

**Comment by lkwg82** [comment]
we should have a test case for windows. So we can be sure.

**Comment by lkwg82** [comment]
> If you want I could give you access to this repo if you want to be a co-maintainer?

Would be nice. But anyway I'll prefer to have a code review by you.

**Comment by lkwg82** [comment]
> By the way does the phantomjs drivers work without errors when using this plugin normally?

It worked for me. But these tests I'll do again later.

**Pull request merged**
