### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by lkwg82**
some little cleanups.

Please see the platform specific tests. It is better to have injectible platform information to run each szenario without running the tests on all platforms.

I did not changed windows and macosx because I dont have a test setup.

Cheers Lars

### CODE REVIEW

**Comment by andidev** [comment]
This looks good except that we should use `Platform.LINUX.is(Platform.getCurrent())` to determine the platform when not running the plugin from the tests. Otherwise it may break compability with the [WebDriverRunner](https://github.com/webdriverextensions/webdriverextensions#cross-browser-test-your-website-with-the-junitrunner).

I'm going to change
```java
public static boolean isLinux() {
    return System.getProperty("os.name").toLowerCase().equals("linux");
}
```

to
```java
public static boolean isLinux() {
	return System.getProperty("webdriverextensions.faked.os.name") != null ? System.getProperty("webdriverextensions.faked.os.name").equals("linux") : Platform.LINUX.is(Platform.getCurrent());
}
```

and do so for all other platforms as well. I'll do the same thing for the `is64Bit()` method as well so that the bit type can be faked as well in the tests.

**Comment by andidev** [comment]
Done! Also I adjusted the first two tests so that they are fully tested from any platform.
I'm gonna further create some tests so that the main usage will be covered. After that I am ready to release this. The tests have really improved! Many thanks for the work!

**Comment by lkwg82** [comment]
Why do you think the system properties are only set in the tests correctly. From what I know this valid for test runs and usual runs. But maybe I missed something.

**Comment by andidev** [comment]
Actually I don't think your solution using `os.name` is wrong and works both for tests and real runs. My problem with it is that it does not exactly use the same logic to identify the platform as the Platform class uses in the selenium framework. And the Platform class is used in another project I'm hosting and that project is depending on this project. Therefore it is important to use the same method to retrieve the platform. 

Though I think that seleniums Platform class is actually parsing the "os.name" system property so maybe an easier solution would have been to keep the original code and modify the "os.os.name" property.

**Comment by lkwg82** [comment]
I read the code and you are right. It is the same, so leave the selenium implementation. Both ways allows to go the way with test I proposed. So we can run all platform tests on all platforms ;).

Great!

**Pull request merged**
