### PR TITLE
Extracting one bin from package of many

### PR DESCRIPTION
**Pull request by lkwg82**
I implemented the extraction of one binary from a package (tar.bz2) given by a pattern.

so phantomjs...tar.bz2 with many files will result in only one given by `fileMatchInside` configuration in repository.json.

Thats why currently one test fails (it fetches the global not adjusted repository.json, see c2dc5b4)

### CODE REVIEW

**Comment by andidev** [comment]
Just tested it and it seems to get a NullPointerException with the local repository.json files as well in the testConfigurationInstallAllLatestDrivers and testConfigurationExtractPhantomJSDriverFromTarBz2 test.


```
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 88.534 sec <<< FAILURE!
testConfigurationExtractPhantomJSDriverFromTarBz2(com.github.webdriverextensions.InstallDriversMojoTest)  Time elapsed: 79.324 sec  <<< ERROR!
java.lang.NullPointerException
	at com.github.webdriverextensions.InstallDriversMojo.extractDriver(InstallDriversMojo.java:236)
	at com.github.webdriverextensions.InstallDriversMojo.execute(InstallDriversMojo.java:185)
	at com.github.webdriverextensions.InstallDriversMojoTest.testConfigurationExtractPhantomJSDriverFromTarBz2(InstallDriversMojoTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testConfigurationInstallAllLatestDrivers(com.github.webdriverextensions.InstallDriversMojoTest)  Time elapsed: 8.625 sec  <<< ERROR!
java.lang.NullPointerException
	at com.github.webdriverextensions.InstallDriversMojo.extractDriver(InstallDriversMojo.java:236)
	at com.github.webdriverextensions.InstallDriversMojo.execute(InstallDriversMojo.java:185)
	at com.github.webdriverextensions.InstallDriversMojoTest.testConfigurationInstallAllLatestDrivers(InstallDriversMojoTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

**Comment by lkwg82** [comment]
It fails because there are some differences on osx with file probing, I'm debugging with travis ci as I dont have a machine ;( (see https://bugs.openjdk.java.net/browse/JDK-8129632)

**Comment by lkwg82** [comment]
It is a lot more than just adding this tiny feature. Hope you like my effort. 

If you dont like it (this is acceptable) I'll publish on my own.

**Comment by andidev** [comment]
You seem to know what you are doing! I allways wanted to refactor the code since it was really messy. I'm gonna try reviewing your changes tonight. If it does not break any backward compatibility I'll release it right away.
By an initial look it looks really nice! Many thanks for the work! I'll mention you in the release notes.

**Comment by andidev** [comment]
So I discovered at least three issues with this PR:
### Issue 1

Running config
```xml
<drivers>
    <driver>
        <name>internetexplorerdriver</name>
        <version>2.47</version>
    </driver>
</drivers>
```

...from a mac results with error
```bash
[ERROR] Failed to execute goal com.github.webdriverextensions:webdriverextensions-maven-plugin:1.1.1-SNAPSHOT:install-drivers (default-cli) on project test-tjp-admin: could not found driver: {"name":"internetexplorerdriver","platform":"mac","bit":"32","version":"2.47"} -> [Help 1]
```

...since it tries to download an internetexplorerdriver for the platform mac. When it actually should ignore the download since there is no such driver in the repository.



### Issue 2

Running config
```xml
<drivers>
	<driver>
		<name>chromedriver</name>
		<platform>windows</platform>
		<version>2.19.0</version>
	</driver>
</drivers>
```

...always results with downloading the driver
```bash
[INFO] chromedriver-windows-32bit version 2.19.0
[INFO]   Downloading http://chromedriver.storage.googleapis.com/2.19/chromedriver_win32.zip -> /var/folders/mc/fd7bwdvd4c19wwhw0dmt2ngm0000gn/T/InstallDriversMojo/chromedriver_2.19.0__2.19_chromedriver_win32.zip
[INFO]   Installing chromedriver-windows-32bit
```

...even though the driver is already downloaded. The same issue occures when downloading the internetexplorerdriver with config
```xml
<driver>
    <name>internetexplorerdriver</name>
    <platform>windows</platform>
    <version>2.47.0</version>
</driver>
```



There is lots of improvements in this PR so I am still gonna try merging it. Though the issues still needs to be fixed before a release. I'm gonna try to improve the testcases for basic usecases of the plugin and try to fix the issues as soon as I have time.

**Comment by andidev** [comment]
I have commited a test in [commit](https://github.com/webdriverextensions/webdriverextensions-maven-plugin/commit/d7ab3ceb59ed6ca11d05d545d50137bfe3c63a17) which tests issue1 and fails on at least on osx. I think the test will fail in windows and linux as well. This needs to be fixed before I can release your PR. I think the reason is because the "could not found driver" exception should not always be thrown in [Repository.java at](https://github.com/webdriverextensions/webdriverextensions-maven-plugin/blob/master/src/main/java/com/github/webdriverextensions/Repository.java#L138)

**Comment by andidev** [comment]
I just did fix both issues in [this commit](https://github.com/webdriverextensions/webdriverextensions-maven-plugin/commit/906b8d8295f012961cb307356fc5bb656cfa0573) and everything seems nice. Not the most beatutiful code but it works. Maybe you know a better way to handle this without a major refactoring job.

So I'm going to release this if you do nit have anything more to add?

**Comment by lkwg82** [comment]
Thx ... I'll check it out. 
Would you be so nice and connect travis ci with your repos (config was included).

**Comment by andidev** [comment]
Not that familiar with that but I'll try to add it right away. Thanks!

**Pull request merged**
